version: '3.8'

services:
  nexopos:
    build: .
    container_name: quantum_pos
    restart: always
    depends_on:
      - db
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=nexopos
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "80:80"
    networks:
      - nexopos_network

  db:
    image: mysql:8
    container_name: quantum_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nexopos
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nexopos_network

  redis:
    image: redis:alpine
    container_name: quantum_cache
    restart: always
    networks:
      - nexopos_network

volumes:
  db_data:

networks:
  nexopos_network:

